#include "presentation/ability/AbilityPresentationContent.h"

#include "presentation/ability/gravityAnomaly/GravityAnomalyPresentationProfile.h"
#include "presentation/ability/infernoSpray/InfernoSprayPresentationProfile.h"
#include "presentation/ability/rocket/RocketPresentationProfile.h"
#include "presentation/ability/overdriveCore/OverdriveCorePresentationProfile.h"
#include "presentation/ability/nullPulse/NullPulsePresentationProfile.h"
#include "presentation/ability/orbitalDrones/OrbitalDronesPresentationProfile.h"
#include "presentation/ability/phaseDrift/PhaseDriftPresentationProfile.h"
#include "presentation/ability/hullShock/HullShockPresentationProfile.h"
#include "presentation/ability/shieldHarvest/ShieldHarvestPresentationProfile.h"
#include "presentation/ability/sunBeam/SunBeamPresentationProfile.h"
#include "presentation/ability/relayPrism/RelayPrismPresentationProfile.h"
#include "presentation/ability/railBurst/RailBurstPresentationProfile.h"
#include "presentation/ability/crescentReaver/CrescentReaverPresentationProfile.h"
#include "presentation/ability/aegisReaver/AegisReaverPresentationProfile.h"
#include "presentation/ability/mineLayer/MineLayerPresentationProfile.h"
#include "presentation/ability/energySpear/EnergySpearPresentationProfile.h"
#include "presentation/ability/scorchDrive/ScorchDrivePresentationProfile.h"
#include "presentation/ability/ionStorm/IonStormPresentationProfile.h"
#include "presentation/ability/directionalBarrier/DirectionalBarrierPresentationProfile.h"
#include "presentation/ability/glacialPressure/GlacialPressurePresentationProfile.h"
#include "presentation/ability/chainLightning/ChainLightningPresentationProfile.h"
#include "presentation/ability/stormMark/StormMarkPresentationProfile.h"
#include "presentation/ability/voidGate/VoidGatePresentationProfile.h"
#include "presentation/ability/cryostasis/CryostasisPresentationProfile.h"
#include "presentation/ability/frostMaelstrom/FrostMaelstromPresentationProfile.h"
#include "presentation/ability/frozenThrong/FrozenThrongPresentationProfile.h"
#include "presentation/ability/combatSentry/CombatSentryPresentationProfile.h"
#include "presentation/ability/nanoPlague/NanoPlaguePresentationProfile.h"
#include "presentation/ability/astralSurge/AstralSurgePresentationProfile.h"
#include "presentation/ability/wingSentinels/WingSentinelsPresentationProfile.h"
#include "presentation/ability/returnProtocol/ReturnProtocolPresentationProfile.h"
#include "presentation/ability/crystalBarricade/CrystalBarricadePresentationProfile.h"
#include "presentation/ability/solarBombardment/SolarBombardmentPresentationProfile.h"
#include "presentation/ability/strikeRun/StrikeRunPresentationProfile.h"
#include "presentation/ability/blastback/BlastbackPresentationProfile.h"
#include "presentation/ability/seismicCharge/SeismicChargePresentationProfile.h"
#include "presentation/ability/arcScythes/ArcScythesPresentationProfile.h"
#include "presentation/ability/temporalConvergence/TemporalConvergencePresentationProfile.h"
#include "presentation/ability/closedCircuit/ClosedCircuitPresentationProfile.h"
#include "presentation/ability/foldspaceArena/FoldspaceArenaPresentationProfile.h"
#include "presentation/ability/cryoBola/CryoBolaPresentationProfile.h"
#include "presentation/ability/inertialWake/InertialWakePresentationProfile.h"
#include "presentation/ability/shieldGraft/ShieldGraftPresentationProfile.h"
#include "presentation/ability/emberSwarm/EmberSwarmPresentationProfile.h"
#include "presentation/ability/lanceDrive/LanceDrivePresentationProfile.h"
#include "presentation/ability/reclaimerProtocol/ReclaimerProtocolPresentationProfile.h"

namespace ly
{
	bool RegisterGameAbilityPresentationContent()
	{
		static const bool registered =
			RegisterGravityAnomalyPresentationProfiles() &&
			RegisterRocketPresentationProfiles() &&
			RegisterOverdriveCorePresentationProfiles() &&
			RegisterNullPulsePresentationProfiles() &&
			RegisterOrbitalDronesPresentationProfiles() &&
			RegisterPhaseDriftPresentationProfiles() &&
			RegisterShieldHarvestPresentationProfiles() &&
			RegisterHullShockPresentationProfiles() &&
			RegisterSunBeamPresentationProfiles() &&
			RegisterInfernoSprayPresentationProfiles() &&
			RegisterRelayPrismPresentationProfiles() &&
			RegisterRailBurstPresentationProfiles() &&
			RegisterCrescentReaverPresentationProfiles() &&
			RegisterAegisReaverPresentationProfiles() &&
			RegisterMineLayerPresentationProfiles() &&
			RegisterEnergySpearPresentationProfiles() &&
			RegisterScorchDrivePresentationProfiles() &&
			RegisterDirectionalBarrierPresentationProfiles() &&
			RegisterIonStormPresentationProfiles() &&
			RegisterGlacialPressurePresentationProfiles() &&
			RegisterChainLightningPresentationProfiles() &&
			RegisterStormMarkPresentationProfiles() &&
			RegisterCryostasisPresentationProfiles() &&
			RegisterVoidGatePresentationProfiles() &&
			RegisterFrostMaelstromPresentationProfiles() &&
			RegisterFrozenThrongPresentationProfiles() &&
			RegisterCombatSentryPresentationProfiles() &&
			RegisterNanoPlaguePresentationProfiles() &&
			RegisterAstralSurgePresentationProfiles() &&
			RegisterWingSentinelsPresentationProfiles() &&
			RegisterReturnProtocolPresentationProfiles() &&
			RegisterCrystalBarricadePresentationProfiles() &&
			RegisterSolarBombardmentPresentationProfiles() &&
			RegisterStrikeRunPresentationProfiles() &&
			RegisterBlastbackPresentationProfiles() &&
			RegisterSeismicChargePresentationProfiles() &&
			RegisterArcScythesPresentationProfiles() &&
			RegisterTemporalConvergencePresentationProfiles() &&
			RegisterClosedCircuitPresentationProfiles() &&
			RegisterFoldspaceArenaPresentationProfiles() &&
			RegisterCryoBolaPresentationProfiles() &&
			RegisterInertialWakePresentationProfiles() &&
			RegisterShieldGraftPresentationProfiles() &&
			RegisterEmberSwarmPresentationProfiles() &&
			RegisterLanceDrivePresentationProfiles() &&
			RegisterReclaimerProtocolPresentationProfiles();
		return registered;
	}
}
